import type { EventCategory, Registration, SymposiumEvent, TeamMember } from "@/lib/types"

/**
 * DEMO CONTENT — used only while Supabase env keys are still placeholders.
 * Once .env.local is filled in and scripts/003_seed.sql has been run, every
 * page reads from the database instead and this file is never touched.
 * ORGANISERS: the same content exists in scripts/003_seed.sql.
 */

export const demoCategories: EventCategory[] = [
  {
    id: "cat-technical",
    name: "Technical",
    slug: "technical",
    description: "Code, break, defend and present. Events that test engineering depth.",
    active: true,
    display_order: 1,
    event_count: 6,
  },
  {
    id: "cat-non-technical",
    name: "Non-Technical",
    slug: "non-technical",
    description: "Strategy, speed and chaos. Events built for the crowd.",
    active: true,
    display_order: 2,
    event_count: 5,
  },
]

function ev(e: Partial<SymposiumEvent> & Pick<SymposiumEvent, "id" | "name" | "slug">): SymposiumEvent {
  return {
    category_id: "cat-technical",
    category_name: "Technical",
    category_slug: "technical",
    short_description: "",
    description: "",
    rules: [],
    image_url: "/events/generic-technical.png",
    gif_url: null,
    event_date: "2026-03-14",
    start_time: "09:30",
    end_time: "12:30",
    venue: "CSE Block",
    min_team_size: 1,
    max_team_size: 1,
    registration_fee: 100,
    prizes: "Winner ₹3,000 · Runner-up ₹1,500 · Certificates for all finalists",
    coordinator_name: "Aravind S",
    coordinator_phone: "+91 90000 00003",
    status: "active",
    featured: false,
    display_order: 99,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
    registration_count: 0,
    ...e,
  } as SymposiumEvent
}

export const demoEvents: SymposiumEvent[] = [
  ev({
    id: "ev-1",
    name: "Code Doomsday",
    slug: "code-doomsday",
    short_description: "Three rounds of competitive programming under a collapsing timer.",
    description:
      "Code Doomsday is the flagship algorithmic battle of SPARTANZ 3.0. Each round shortens the clock while the problems get heavier — survive elimination, optimise under pressure and finish the final set before the countdown reaches zero. Languages allowed: C, C++, Java, Python.",
    rules: [
      "Individual participation only.",
      "Three rounds: aptitude screening, timed coding, final optimisation round.",
      "Any use of AI assistants, mobile phones or external repositories leads to disqualification.",
      "Partial scoring applies; ties are broken by submission time.",
      "Judges' decision is final.",
    ],
    image_url: "/events/code-doomsday.png",
    venue: "Programming Lab 1, CSE Block",
    start_time: "09:30",
    end_time: "12:30",
    registration_fee: 150,
    prizes: "Winner ₹5,000 · Runner-up ₹2,500 · Certificates for all finalists",
    coordinator_name: "Aravind S",
    coordinator_phone: "+91 90000 00003",
    featured: true,
    display_order: 1,
    registration_count: 128,
  }),
  ev({
    id: "ev-2",
    name: "Breach Protocol",
    slug: "breach-protocol",
    short_description: "A jeopardy-style capture the flag across web, crypto and reversing.",
    description:
      "Breach Protocol is RootSec Club's signature CTF. Teams of two work through a live scoreboard of web exploitation, cryptography, steganography, OSINT and reverse engineering challenges. Flags unlock progressively — the final challenge only appears when half the field has cleared round two.",
    rules: [
      "Teams of 2 participants.",
      "Bring your own laptop; campus Wi-Fi and power will be provided.",
      "Attacking the scoreboard or other teams' machines means instant disqualification.",
      "Flag sharing between teams is prohibited.",
      "Scoreboard freezes 20 minutes before the end.",
    ],
    image_url: "/events/breach-protocol.png",
    venue: "Cyber Security Lab, CSE Block",
    start_time: "10:00",
    end_time: "14:00",
    min_team_size: 2,
    max_team_size: 2,
    registration_fee: 200,
    prizes: "Winner ₹6,000 · Runner-up ₹3,000 · Best first-blood ₹1,000",
    coordinator_name: "Nithya R",
    coordinator_phone: "+91 90000 00004",
    featured: true,
    display_order: 2,
    registration_count: 96,
  }),
  ev({
    id: "ev-3",
    name: "Forensic Gauntlet",
    slug: "forensic-gauntlet",
    short_description: "Reconstruct a simulated breach from disk images, logs and packet captures.",
    description:
      "A compromised workstation, a suspicious PCAP and eleven minutes of missing logs. Teams perform disk and memory triage, build a timeline, identify the initial access vector and submit an incident report. Scoring rewards accuracy of the timeline over speed.",
    rules: [
      "Teams of 2 to 3 participants.",
      "Autopsy, Wireshark and Volatility will be pre-installed on lab machines.",
      "The final incident report must be submitted in the provided template.",
      "Evidence tampering scores zero for that artefact.",
    ],
    image_url: "/events/forensic-gauntlet.png",
    venue: "Cyber Security Lab 2, CSE Block",
    start_time: "10:30",
    end_time: "13:30",
    min_team_size: 2,
    max_team_size: 3,
    registration_fee: 200,
    prizes: "Winner ₹4,000 · Runner-up ₹2,000 · Certificates for all finalists",
    coordinator_name: "Harish M",
    coordinator_phone: "+91 90000 00005",
    display_order: 3,
    registration_count: 54,
  }),
  ev({
    id: "ev-4",
    name: "Paper Storm",
    slug: "paper-storm",
    short_description: "Technical paper presentation on security, AI and emerging systems.",
    description:
      "Present original work in eight minutes plus four minutes of questioning. Tracks include offensive security, privacy engineering, AI safety, secure hardware and post-quantum cryptography. Abstracts are screened before the symposium; shortlisted teams present on stage.",
    rules: [
      "Teams of up to 2 presenters.",
      "Abstract of 250 words must be submitted before 5 March 2026.",
      "8 minutes presentation, 4 minutes Q&A. The bell is final.",
      "Plagiarised submissions are rejected outright.",
      "Slides must be submitted in PDF the previous evening.",
    ],
    image_url: "/events/paper-storm.png",
    venue: "Seminar Hall, Main Block",
    start_time: "09:30",
    end_time: "13:00",
    min_team_size: 1,
    max_team_size: 2,
    registration_fee: 150,
    prizes: "Best paper ₹4,000 · Runner-up ₹2,000 · Publication support for top 3",
    coordinator_name: "Prof. K. Divya",
    coordinator_phone: "+91 90000 00002",
    featured: true,
    display_order: 4,
    registration_count: 71,
  }),
  ev({
    id: "ev-5",
    name: "Debug the Multiverse",
    slug: "debug-the-multiverse",
    short_description: "Broken code from parallel timelines. Fix it before the branch collapses.",
    description:
      "Each round hands you a codebase that almost works. Race to find the fault — off-by-one, race condition, memory leak or a subtly poisoned dependency — and patch it with the fewest lines changed. Minimal diffs score higher than clever rewrites.",
    rules: [
      "Individual participation.",
      "Rounds in C, Python and JavaScript.",
      "Only the provided editor may be used. No internet access.",
      "Scoring: correctness first, then diff size, then time.",
    ],
    image_url: "/events/debug-multiverse.png",
    venue: "Programming Lab 2, CSE Block",
    start_time: "13:30",
    end_time: "15:30",
    registration_fee: 100,
    prizes: "Winner ₹3,000 · Runner-up ₹1,500",
    coordinator_name: "Swetha P",
    coordinator_phone: "+91 90000 00006",
    display_order: 5,
    registration_count: 88,
  }),
  ev({
    id: "ev-6",
    name: "Web Siege",
    slug: "web-siege",
    short_description: "Build a resilient web app in four hours, then defend it from the room.",
    description:
      "A build-and-defend hackathon. Teams ship a small web application against a given brief in the first three hours. In the final hour, teams rotate and attempt to break each other's app — points are scored both for surviving and for finding real vulnerabilities.",
    rules: [
      "Teams of 3 to 4 participants.",
      "Any stack allowed. Starter templates are permitted; pre-written project code is not.",
      "Denial of service attacks during the defence round are not counted.",
      "Every finding must be submitted with reproduction steps.",
    ],
    image_url: "/events/web-siege.png",
    venue: "Innovation Lab, CSE Block",
    start_time: "09:30",
    end_time: "14:30",
    min_team_size: 3,
    max_team_size: 4,
    registration_fee: 300,
    prizes: "Winner ₹8,000 · Runner-up ₹4,000 · Best defence ₹1,500",
    coordinator_name: "Vignesh K",
    coordinator_phone: "+91 90000 00007",
    display_order: 6,
    registration_count: 64,
  }),

  // ---------------- NON-TECHNICAL ----------------
  ev({
    id: "ev-7",
    name: "Meme Infinity",
    slug: "meme-infinity",
    short_description: "A live meme war. Prompts drop every four minutes.",
    description:
      "Two devices, one shared screen and a room that decides your fate. Prompts are revealed live and the crowd's reaction feeds directly into the score. Clean humour only — anything targeting individuals, communities or the institution is removed.",
    rules: [
      "Individual participation.",
      "Bring your own phone or laptop for editing.",
      "No offensive, political or personal content.",
      "Templates from the internet are allowed; pre-made memes are not.",
      "Audience response accounts for 40% of the score.",
    ],
    image_url: "/events/meme-infinity.png",
    category_id: "cat-non-technical",
    category_name: "Non-Technical",
    category_slug: "non-technical",
    venue: "Studio Hall, Main Block",
    start_time: "11:00",
    end_time: "12:30",
    registration_fee: 50,
    prizes: "Winner ₹2,000 · Runner-up ₹1,000",
    coordinator_name: "Divya Bharathi",
    coordinator_phone: "+91 90000 00008",
    featured: true,
    display_order: 7,
    registration_count: 142,
  }),
  ev({
    id: "ev-8",
    name: "Shadow Auction",
    slug: "shadow-auction",
    short_description: "Budgeted bidding war. Build the strongest roster before the purse dies.",
    description:
      "Each team gets a fixed purse and an incomplete player list. Bid, bluff and balance — the catch is that three marquee names are only revealed after half the purse is gone. Final rosters are scored by a panel on balance, value and strategy.",
    rules: [
      "Teams of 2 to 3 participants.",
      "Fixed purse announced at the start. Overspending disqualifies the roster.",
      "A minimum roster composition must be satisfied.",
      "The auctioneer's call is final.",
    ],
    image_url: "/events/shadow-auction.png",
    category_id: "cat-non-technical",
    category_name: "Non-Technical",
    category_slug: "non-technical",
    venue: "Seminar Hall 2, Main Block",
    start_time: "13:30",
    end_time: "15:30",
    min_team_size: 2,
    max_team_size: 3,
    registration_fee: 100,
    prizes: "Winner ₹3,000 · Runner-up ₹1,500",
    coordinator_name: "Karthik R",
    coordinator_phone: "+91 90000 00009",
    display_order: 8,
    registration_count: 77,
  }),
  ev({
    id: "ev-9",
    name: "Cine Cipher",
    slug: "cine-cipher",
    short_description: "Connections, dumb charades and audio rounds — decode the clip.",
    description:
      "A cinema quiz wrapped in cryptography. Rounds include visual connections, reversed audio, one-frame stills and a rapid-fire finale. No buzzers — answers are written and revealed simultaneously, so speed matters less than nerve.",
    rules: [
      "Teams of 2 participants.",
      "Phones are collected before the first round.",
      "Negative marking applies in the rapid-fire round only.",
      "Quizmaster's decision is final.",
    ],
    image_url: "/events/cine-cipher.png",
    category_id: "cat-non-technical",
    category_name: "Non-Technical",
    category_slug: "non-technical",
    venue: "Auditorium Annexe",
    start_time: "10:00",
    end_time: "11:30",
    min_team_size: 2,
    max_team_size: 2,
    registration_fee: 80,
    prizes: "Winner ₹2,500 · Runner-up ₹1,200",
    coordinator_name: "Meenakshi V",
    coordinator_phone: "+91 90000 00010",
    display_order: 9,
    registration_count: 103,
  }),
  ev({
    id: "ev-10",
    name: "Endgame Arena",
    slug: "endgame-arena",
    short_description: "Squad-based mobile gaming knockouts on a live projector feed.",
    description:
      "Squads of four fight through group stages into a projected grand final with live commentary from the RootSec media team. Custom rooms, standard competitive settings, no emulators.",
    rules: [
      "Squads of 4 players.",
      "Mobile devices only. Emulators, triggers and external controllers are banned.",
      "Teaming with other squads results in removal from the bracket.",
      "Room IDs are shared 10 minutes before each match.",
    ],
    image_url: "/events/endgame-arena.png",
    category_id: "cat-non-technical",
    category_name: "Non-Technical",
    category_slug: "non-technical",
    venue: "Gaming Zone, Student Centre",
    start_time: "11:00",
    end_time: "15:00",
    min_team_size: 4,
    max_team_size: 4,
    registration_fee: 200,
    prizes: "Champion squad ₹5,000 · Runner-up ₹2,500 · MVP ₹1,000",
    coordinator_name: "Sanjay T",
    coordinator_phone: "+91 90000 00011",
    display_order: 10,
    registration_count: 156,
  }),
  ev({
    id: "ev-11",
    name: "Treasure Protocol",
    slug: "treasure-protocol",
    short_description: "A campus-wide hunt chained by QR codes and cipher fragments.",
    description:
      "Eleven checkpoints across the campus, each guarded by a cipher fragment that only makes sense once you hold three of them. Teams move on foot, decode in the open and race a shrinking clue budget.",
    rules: [
      "Teams of 3 to 4 participants.",
      "One phone per team for scanning QR checkpoints.",
      "Do not remove, damage or hide clue cards.",
      "Restricted areas marked on the campus map are out of bounds.",
      "Each hint taken costs 5 minutes of final time.",
    ],
    image_url: "/events/treasure-protocol.png",
    category_id: "cat-non-technical",
    category_name: "Non-Technical",
    category_slug: "non-technical",
    venue: "Campus wide · Start at Main Quad",
    start_time: "14:00",
    end_time: "16:00",
    min_team_size: 3,
    max_team_size: 4,
    registration_fee: 120,
    prizes: "Winner ₹3,500 · Runner-up ₹1,800",
    coordinator_name: "Praveen A",
    coordinator_phone: "+91 90000 00012",
    display_order: 11,
    registration_count: 91,
  }),
]

export const demoTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    name: "Dr. A. Ramesh",
    role: "Head of Department",
    category: "Faculty Coordinators",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Leads the CSE — Cyber Security department and chairs the symposium committee.",
    department: "CSE — Cyber Security",
    year: null,
    display_order: 1,
    active: true,
  },
  {
    id: "tm-2",
    name: "Prof. K. Divya",
    role: "Staff Coordinator",
    category: "Faculty Coordinators",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Faculty advisor for RootSec Club and mentor for the paper presentation track.",
    department: "CSE — Cyber Security",
    year: null,
    display_order: 2,
    active: true,
  },
  {
    id: "tm-3",
    name: "Prof. S. Balaji",
    role: "Technical Advisor",
    category: "Faculty Coordinators",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Guides the CTF and forensics tracks.",
    department: "CSE — Cyber Security",
    year: null,
    display_order: 3,
    active: true,
  },
  {
    id: "tm-4",
    name: "Aravind S",
    role: "Student Convenor",
    category: "Organizing Committee",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Runs the symposium floor and owns the master schedule.",
    department: "CSE — Cyber Security",
    year: "IV Year",
    display_order: 1,
    active: true,
  },
  {
    id: "tm-5",
    name: "Nithya R",
    role: "Joint Convenor",
    category: "Organizing Committee",
    photo_url: "/placeholder-user.jpg",
    short_bio: "RootSec Club secretary. Designed the Breach Protocol challenge set.",
    department: "CSE — Cyber Security",
    year: "IV Year",
    display_order: 2,
    active: true,
  },
  {
    id: "tm-6",
    name: "Harish M",
    role: "Forensics Lead",
    category: "Event Coordinators",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Builds the disk and memory artefacts for Forensic Gauntlet.",
    department: "CSE — Cyber Security",
    year: "III Year",
    display_order: 1,
    active: true,
  },
  {
    id: "tm-7",
    name: "Swetha P",
    role: "Coding Events Lead",
    category: "Event Coordinators",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Sets the problem ladder for Code Doomsday and Debug the Multiverse.",
    department: "CSE — Cyber Security",
    year: "III Year",
    display_order: 2,
    active: true,
  },
  {
    id: "tm-8",
    name: "Vignesh K",
    role: "Infrastructure",
    category: "Technical Team",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Keeps the scoreboard, lab images and network up during the CTF.",
    department: "CSE — Cyber Security",
    year: "III Year",
    display_order: 1,
    active: true,
  },
  {
    id: "tm-9",
    name: "Rithika N",
    role: "Web Team",
    category: "Technical Team",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Maintains this site and the registration pipeline.",
    department: "CSE — Cyber Security",
    year: "II Year",
    display_order: 2,
    active: true,
  },
  {
    id: "tm-10",
    name: "Divya Bharathi",
    role: "Design Lead",
    category: "Design Team",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Created the SPARTANZ 3.0 visual identity and stage graphics.",
    department: "CSE — Cyber Security",
    year: "II Year",
    display_order: 1,
    active: true,
  },
  {
    id: "tm-11",
    name: "Sanjay T",
    role: "Media Lead",
    category: "Media Team",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Live commentary, reels and the aftermovie.",
    department: "CSE — Cyber Security",
    year: "II Year",
    display_order: 1,
    active: true,
  },
  {
    id: "tm-12",
    name: "Meenakshi V",
    role: "Hospitality Lead",
    category: "Hospitality Team",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Handles guest arrivals, refreshments and the judges' lounge.",
    department: "CSE — Cyber Security",
    year: "II Year",
    display_order: 1,
    active: true,
  },
  {
    id: "tm-13",
    name: "Praveen A",
    role: "Registration Lead",
    category: "Registration Team",
    photo_url: "/placeholder-user.jpg",
    short_bio: "Runs the desk, verifies teams and issues participation certificates.",
    department: "CSE — Cyber Security",
    year: "III Year",
    display_order: 1,
    active: true,
  },
  {
    id: "tm-14",
    name: "Karthik R",
    role: "Registration Support",
    category: "Registration Team",
    photo_url: "/placeholder-user.jpg",
    short_bio: "On-spot registrations and payment reconciliation.",
    department: "CSE — Cyber Security",
    year: "I Year",
    display_order: 2,
    active: true,
  },
]

export const demoRegistrations: Registration[] = [
  {
    id: "reg-1",
    reference_code: "SPZ-8F41K2",
    user_id: "demo-user-1",
    event_id: "ev-1",
    full_name: "Ashwin Kumar",
    email: "ashwin.k@example.edu.in",
    phone: "+91 98400 11223",
    college: "New Prince Shri Bhavani College of Engineering",
    department: "CSE — Cyber Security",
    year: "III Year",
    team_name: null,
    status: "CONFIRMED",
    created_at: "2026-02-18T06:12:00Z",
    event_name: "Code Doomsday",
    event_category: "Technical",
  },
  {
    id: "reg-2",
    reference_code: "SPZ-2J09PL",
    user_id: "demo-user-2",
    event_id: "ev-2",
    full_name: "Fathima Noor",
    email: "fathima.n@example.edu.in",
    phone: "+91 98400 44551",
    college: "Sri Sairam Engineering College",
    department: "Information Technology",
    year: "IV Year",
    team_name: "Null Terminators",
    status: "REGISTERED",
    created_at: "2026-02-19T11:40:00Z",
    event_name: "Breach Protocol",
    event_category: "Technical",
    members: [{ name: "Fathima Noor" }, { name: "Ijaz Ahmed" }],
  },
  {
    id: "reg-3",
    reference_code: "SPZ-77XQ1A",
    user_id: "demo-user-3",
    event_id: "ev-10",
    full_name: "Gokul Prasath",
    email: "gokul.p@example.edu.in",
    phone: "+91 98400 77219",
    college: "Rajalakshmi Institute of Technology",
    department: "CSE",
    year: "II Year",
    team_name: "Wraith Squad",
    status: "ATTENDED",
    created_at: "2026-02-20T04:05:00Z",
    event_name: "Endgame Arena",
    event_category: "Non-Technical",
    members: [{ name: "Gokul Prasath" }, { name: "Deepak R" }, { name: "Sri Hari" }, { name: "Yogesh V" }],
  },
  {
    id: "reg-4",
    reference_code: "SPZ-5MB3ZQ",
    user_id: "demo-user-4",
    event_id: "ev-7",
    full_name: "Lavanya S",
    email: "lavanya.s@example.edu.in",
    phone: "+91 98400 90881",
    college: "New Prince Shri Bhavani College of Engineering",
    department: "CSE — Cyber Security",
    year: "I Year",
    team_name: null,
    status: "REGISTERED",
    created_at: "2026-02-21T09:22:00Z",
    event_name: "Meme Infinity",
    event_category: "Non-Technical",
  },
  {
    id: "reg-5",
    reference_code: "SPZ-91TR6C",
    user_id: "demo-user-5",
    event_id: "ev-4",
    full_name: "Mohammed Rizwan",
    email: "rizwan.m@example.edu.in",
    phone: "+91 98400 30012",
    college: "Velammal Engineering College",
    department: "CSE",
    year: "IV Year",
    team_name: "Cipherline",
    status: "CANCELLED",
    created_at: "2026-02-22T13:48:00Z",
    event_name: "Paper Storm",
    event_category: "Technical",
    members: [{ name: "Mohammed Rizwan" }, { name: "Sneha Iyer" }],
  },
]

export const demoStats = {
  totalRegistrations: demoEvents.reduce((sum, e) => sum + (e.registration_count ?? 0), 0),
  technicalRegistrations: demoEvents
    .filter((e) => e.category_slug === "technical")
    .reduce((sum, e) => sum + (e.registration_count ?? 0), 0),
  nonTechnicalRegistrations: demoEvents
    .filter((e) => e.category_slug === "non-technical")
    .reduce((sum, e) => sum + (e.registration_count ?? 0), 0),
  totalEvents: demoEvents.length,
  activeEvents: demoEvents.filter((e) => e.status === "active").length,
  totalUsers: 486,
  totalTeamMembers: demoTeamMembers.length,
}
