import type {
  EventCategory,
  EventItem,
  SiteSettings,
  TeamMember,
} from './types'

// ---- CONFIGURABLE CONTENT ----
// Organizers can replace dates, venue, names, images, GIFs, coordinators.

export const SEED_SETTINGS: SiteSettings = {
  symposiumName: 'SPARTANZ 3.0',
  subtitle: 'Department Symposium',
  college: 'New Prince Shri Bhavani College of Engineering',
  department: 'CSE — Cyber Security',
  club: 'RootSec Club',
  theme: 'Avengers: Doomsday Inspired',
  date: 'March 14, 2026',
  venue: 'Main Auditorium & CSE Block, NPSBCE Campus',
  contactEmail: 'spartanz@rootsec.dev',
  phone: '+91 98765 43210',
  socials: [
    { label: 'Instagram', url: 'https://instagram.com' },
    { label: 'LinkedIn', url: 'https://linkedin.com' },
    { label: 'GitHub', url: 'https://github.com' },
  ],
  heroTagline: 'The dimension breaks. The battle begins.',
  countdownDate: '2026-03-14T09:00:00',
  registrationOpen: true,
}

export const SEED_CATEGORIES: EventCategory[] = [
  {
    id: 'cat-tech',
    name: 'Technical',
    slug: 'technical',
    active: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-nontech',
    name: 'Non-Technical',
    slug: 'non-technical',
    active: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

const now = new Date().toISOString()

export const SEED_EVENTS: EventItem[] = [
  {
    id: 'ev-ctf',
    name: 'Doomsday Protocol (CTF)',
    slug: 'doomsday-protocol-ctf',
    category: 'technical',
    shortDescription:
      'A live capture-the-flag gauntlet. Breach the defenses, capture the flags, survive the fall.',
    description:
      'Doomsday Protocol is the flagship Capture The Flag competition of SPARTANZ 3.0. Teams battle through categories spanning web exploitation, cryptography, reverse engineering, forensics and binary exploitation. Solve challenges to capture flags and climb the live leaderboard before the timeline collapses.',
    rules: [
      'Teams of 2 members.',
      'No attacking the scoring infrastructure or other teams.',
      'Flag sharing between teams results in disqualification.',
      'Internet access is allowed; automated brute-force on the platform is not.',
      'Judges decisions are final.',
    ],
    image: '/events/ctf.png',
    date: 'March 14, 2026',
    startTime: '10:00 AM',
    endTime: '02:00 PM',
    venue: 'Cyber Lab 1, CSE Block',
    teamSize: { min: 2, max: 2 },
    registrationFee: 150,
    prizes: '₹10,000 pool • Winner ₹6,000 • Runner-up ₹4,000',
    coordinator: { name: 'Arjun Menon', phone: '+91 98765 11111' },
    status: 'active',
    displayOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ev-hack',
    name: 'Endgame Hackathon',
    slug: 'endgame-hackathon',
    category: 'technical',
    shortDescription:
      'Six hours. One prompt. Build a defense before the dimension collapses.',
    description:
      'Endgame is a rapid-fire hackathon where teams ship a working prototype around a security or resilience theme revealed on the spot. Judged on innovation, technical depth, and demo quality. Bring your own laptops; power and network provided.',
    rules: [
      'Teams of 3 to 4 members.',
      'Problem statement revealed at the start.',
      'All code must be written during the event.',
      'Open-source libraries are allowed with attribution.',
      'Final demo limited to 4 minutes per team.',
    ],
    image: '/events/hackathon.png',
    date: 'March 14, 2026',
    startTime: '09:30 AM',
    endTime: '04:30 PM',
    venue: 'Innovation Hall, CSE Block',
    teamSize: { min: 3, max: 4 },
    registrationFee: 200,
    prizes: '₹15,000 pool • Winner ₹9,000 • Runner-up ₹6,000',
    coordinator: { name: 'Priya Raman', phone: '+91 98765 22222' },
    status: 'active',
    displayOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ev-web',
    name: 'Interface Wars (Web Dev)',
    slug: 'interface-wars-web-dev',
    category: 'technical',
    shortDescription:
      'Design and build a themed web experience under the clock. Pixels are your weapon.',
    description:
      'Interface Wars pits front-end warriors against each other to build a responsive, accessible web interface from a themed brief. Judged on design fidelity, responsiveness, accessibility and code quality.',
    rules: [
      'Solo or teams of 2.',
      'Any framework or vanilla stack allowed.',
      'Design brief handed out at the start.',
      'Must be responsive from 320px upward.',
      'AI code assistants are permitted but the build must be original.',
    ],
    image: '/events/webdev.png',
    date: 'March 14, 2026',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    venue: 'Lab 3, CSE Block',
    teamSize: { min: 1, max: 2 },
    registrationFee: 120,
    prizes: '₹6,000 pool • Winner ₹4,000 • Runner-up ₹2,000',
    coordinator: { name: 'Kavya Suresh', phone: '+91 98765 33333' },
    status: 'active',
    displayOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ev-paper',
    name: 'Vision Nexus (Paper Presentation)',
    slug: 'vision-nexus-paper-presentation',
    category: 'technical',
    shortDescription:
      'Present bold ideas in cyber security, AI and emerging tech to an expert panel.',
    description:
      'Vision Nexus is the technical paper presentation track. Participants present original research or well-argued surveys in domains such as cyber security, AI/ML, cloud, and emerging tech. Slides and a short abstract must be submitted in advance.',
    rules: [
      'Solo or teams of 2.',
      'Submit abstract (max 250 words) before the deadline.',
      'Presentation time: 8 minutes + 2 minutes Q&A.',
      'Plagiarised work is disqualified.',
      'Bring slides in PDF on a USB drive as backup.',
    ],
    image: '/events/paper.png',
    date: 'March 14, 2026',
    startTime: '10:30 AM',
    endTime: '01:30 PM',
    venue: 'Seminar Hall 2',
    teamSize: { min: 1, max: 2 },
    registrationFee: 100,
    prizes: '₹5,000 pool • Winner ₹3,000 • Runner-up ₹2,000',
    coordinator: { name: 'Rahul Nair', phone: '+91 98765 44444' },
    status: 'active',
    displayOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ev-gaming',
    name: 'Battle Arena (Esports)',
    slug: 'battle-arena-esports',
    category: 'non-technical',
    shortDescription:
      'Squad up and dominate the arena in our high-stakes gaming showdown.',
    description:
      'Battle Arena is the esports showdown of SPARTANZ 3.0. Compete in a bracket-style tournament for the crown. Peripherals provided; bring your reflexes. Fair-play rules strictly enforced.',
    rules: [
      'Teams as per the game format announced.',
      'No cheats, macros, or third-party tools.',
      'Match schedule published on the day.',
      'Unsportsmanlike conduct leads to disqualification.',
      'Coordinators resolve all disputes on the spot.',
    ],
    image: '/events/gaming.png',
    date: 'March 14, 2026',
    startTime: '12:00 PM',
    endTime: '04:00 PM',
    venue: 'Recreation Center',
    teamSize: { min: 1, max: 4 },
    registrationFee: 100,
    prizes: '₹8,000 pool • Winner ₹5,000 • Runner-up ₹3,000',
    coordinator: { name: 'Sanjay Kumar', phone: '+91 98765 55555' },
    status: 'active',
    displayOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ev-treasure',
    name: 'Cipher Hunt (Treasure Hunt)',
    slug: 'cipher-hunt-treasure-hunt',
    category: 'non-technical',
    shortDescription:
      'Decode cryptic clues across campus in a race against the doomsday clock.',
    description:
      'Cipher Hunt is a campus-wide treasure hunt woven with cryptography, riddles, and logic puzzles. Teams follow a chain of clues; the first to reach the final vault wins. Wits over speed.',
    rules: [
      'Teams of 3 to 5 members.',
      'Do not tamper with clues meant for other teams.',
      'Phones allowed only when a clue permits it.',
      'Stay within the campus boundary.',
      'First team to solve the final clue wins.',
    ],
    image: '/events/treasure.png',
    date: 'March 14, 2026',
    startTime: '01:00 PM',
    endTime: '03:30 PM',
    venue: 'Starts at Main Quad',
    teamSize: { min: 3, max: 5 },
    registrationFee: 80,
    prizes: '₹4,000 pool • Winner ₹2,500 • Runner-up ₹1,500',
    coordinator: { name: 'Meera Iyer', phone: '+91 98765 66666' },
    status: 'active',
    displayOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ev-quiz',
    name: 'Mind Vault (Tech Quiz)',
    slug: 'mind-vault-tech-quiz',
    category: 'non-technical',
    shortDescription:
      'A fast, buzzer-driven quiz spanning tech, cyber, pop-culture and beyond.',
    description:
      'Mind Vault is a multi-round quiz that blends technology trivia, cyber security lore and pop-culture. A written prelims round shortlists teams for a live, buzzer-based final on stage.',
    rules: [
      'Teams of 2 members.',
      'Prelims is a written round; top teams reach the final.',
      'No phones or notes during rounds.',
      'Quiz master decisions are final.',
      'Negative marking applies in the final.',
    ],
    image: '/events/quiz.png',
    date: 'March 14, 2026',
    startTime: '11:30 AM',
    endTime: '01:00 PM',
    venue: 'Main Auditorium',
    teamSize: { min: 2, max: 2 },
    registrationFee: 60,
    prizes: '₹3,000 pool • Winner ₹2,000 • Runner-up ₹1,000',
    coordinator: { name: 'Divya Prakash', phone: '+91 98765 77777' },
    status: 'active',
    displayOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
]

const teamPhoto = '/team/avatar-1.png'

export const SEED_TEAM: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Dr. S. Ramesh',
    role: 'Head of Department, CSE — Cyber Security',
    category: 'faculty-coordinators',
    photo: teamPhoto,
    shortBio: 'Guiding force behind SPARTANZ and the RootSec initiative.',
    department: 'CSE — Cyber Security',
    displayOrder: 1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-2',
    name: 'Prof. Anitha Krishnan',
    role: 'Faculty Coordinator',
    category: 'faculty-coordinators',
    photo: teamPhoto,
    shortBio: 'Mentor for the RootSec Club and symposium operations.',
    department: 'CSE — Cyber Security',
    displayOrder: 2,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-3',
    name: 'Aravind Balaji',
    role: 'Symposium Lead',
    category: 'organizing-committee',
    photo: teamPhoto,
    shortBio: 'Leads end-to-end planning and execution of SPARTANZ 3.0.',
    department: 'CSE — Cyber Security',
    year: 'Final Year',
    displayOrder: 1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-4',
    name: 'Nithya Sundar',
    role: 'Operations Head',
    category: 'organizing-committee',
    photo: teamPhoto,
    department: 'CSE — Cyber Security',
    year: 'Third Year',
    displayOrder: 2,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-5',
    name: 'Arjun Menon',
    role: 'CTF & Technical Events',
    category: 'event-coordinators',
    photo: teamPhoto,
    department: 'CSE — Cyber Security',
    year: 'Final Year',
    displayOrder: 1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-6',
    name: 'Kavya Suresh',
    role: 'Web & Design Events',
    category: 'event-coordinators',
    photo: teamPhoto,
    department: 'CSE — Cyber Security',
    year: 'Third Year',
    displayOrder: 2,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-7',
    name: 'Vikram Das',
    role: 'Infrastructure & Networking',
    category: 'technical-team',
    photo: teamPhoto,
    department: 'CSE — Cyber Security',
    year: 'Third Year',
    displayOrder: 1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-8',
    name: 'Sneha Pillai',
    role: 'Creative Lead',
    category: 'design-team',
    photo: teamPhoto,
    department: 'CSE — Cyber Security',
    year: 'Second Year',
    displayOrder: 1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-9',
    name: 'Rohit Varma',
    role: 'Photography & Reels',
    category: 'media-team',
    photo: teamPhoto,
    department: 'CSE — Cyber Security',
    year: 'Second Year',
    displayOrder: 1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-10',
    name: 'Lakshmi Narayan',
    role: 'Guest & Hospitality',
    category: 'hospitality-team',
    photo: teamPhoto,
    department: 'CSE — Cyber Security',
    year: 'Second Year',
    displayOrder: 1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tm-11',
    name: 'Deepak Raj',
    role: 'On-site Registration',
    category: 'registration-team',
    photo: teamPhoto,
    department: 'CSE — Cyber Security',
    year: 'First Year',
    displayOrder: 1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
]
